apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: wy-metrics-role
rules:
- apiGroups: ["metrics.k8s.io"] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: wy-metrics-clusterrole
rules:
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["list"]

--- 

apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
kind: ClusterRole
metadata:
  name: read-pods
  namespace: default
subjects:
- kind: User
  name: wy # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: wy-metrics-clusterrole # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io