apiVersion: v1
kind: Service
metadata:
  name: redis-srv
  namespace: demo
  labels:
    app: redis
spec:
  selector:
    app: redis
  type: LoadBalancer
  ports:
  - port: 6379
    name: redis-srv-port
    targetPort: 6379
    nodePort: 31111

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: demo
spec:
  serviceName: redis
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        resources:
          limits:
            memory: "128Mi"
            cpu: "0.2"
          requests:
            memory: "128Mi"
            cpu: "0.1"
        ports:
        - containerPort: 6379
  replicas: 1
  updateStrategy:
    type: RollingUpdate
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: demo
  labels:
    app: helloworld
    type: what
spec:
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: hellojqk/helloworld:latest
        resources:
          limits:
            memory: "80Mi"
            cpu: "0.15"
          requests:
            memory: "40Mi"
            cpu: "0.1"
        args:
          - "-port"
          - "8888"
        ports:
        - containerPort: 8888
        imagePullPolicy: Always
        # lifecycle:
        #   postStart:
        #     exec:
        #       command:
        #         - "ls -l"
      restartPolicy: Always
  revisionHistoryLimit: 10
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---

kind: Service
apiVersion: v1
metadata:
  name:  helloworld-srv
  namespace: demo
spec:
  selector:
    app:  helloworld
  type: LoadBalancer
  ports:
  - name: helloworldport
    protocol: TCP
    port:  8888
    targetPort:  8888
    nodePort: 32540