kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-runner-rb
  namespace: default #限定运行的命名空间
roleRef:
  kind: ClusterRole #角色级别
  name: gitlab-runner #角色名
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: User #假设每个命名空间只需要一个这样的用户 gitlab-runner用户场景
    name: wy #用户名
    apiGroup: rbac.authorization.k8s.io #todo ？仅用来驱动授权决策 参考 https://kubernetes.io/docs/reference/access-authn-authz/rbac/ 第一屏
  # - kind: Group #对应证书中的用户组 假设开发组 运维组 测试组等
  #   name: group1
  #   apiGroup: rbac.authorization.k8s.io