apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: default
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "6060"
    spec:
      containers:
        - name: app
          image: hellojqk/app:0.0.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
            requests:
              memory: "64Mi"
              cpu: "100m"
          ports:
            - containerPort: 8888
            - containerPort: 6060
          imagePullPolicy: Never
  replicas: 10

---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: default
spec:
  selector:
    app: app
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 31888
  type: NodePort
---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: app-ing
#   namespace: default
# spec:
#   rules:
#     - http:
#         paths:
#           - path: /testpath
#             backend:
#               serviceName: test
#               servicePort: 80
