

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-runner
rules:
  - apiGroups: ["","apps","extensions","batch"]
    resources: 
      - configmaps
      - endpoints
      - limitranges
      - persistentvolumeclaims   
      - nodes
      - pods 
      - podtemplates   
      - replicationcontrollers 
      - resourcequotas 
      - services 
      - daemonsets
      - deployments
      - replicasets
      - statefulsets 
      - cronjobs 
      - jobs 
      - replicasets
    verbs: ["get", "list", "watch", "create", "update", "patch"] #["get", "list", "watch", "create", "update", "patch", "delete"]