apiVersion: v1
kind: Service
metadata:
  name: {POD}-svc
  labels:
    debug: {POD}
spec:
  selector:
    debug: {POD}
  ports:
  - port: 6060
    targetPort: 6060
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {POD}-route
  labels:
    debug: {POD}
  namespace: tr
spec:
  rules:
    - host: {POD}.cab7b4da4476242bc9ac8743854ce1325.cn-shanghai.alicontainer.com
      http:
        paths:
          - backend:
              serviceName: {POD}-svc
              servicePort: 6060
            path: /
  